/////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Tencent is pleased to support the open source community by making libpag available.
//
//  Copyright (C) 2026 Tencent. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  unless required by applicable law or agreed to in writing, software distributed under the
//  license is distributed on an "as is" basis, without warranties or conditions of any kind,
//  either express or implied. see the license for the specific language governing permissions
//  and limitations under the license.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

#include "pagx/HTMLExporter.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include "pagx/html/HTMLBuilder.h"
#include "pagx/html/HTMLStyleExtractor.h"
#include "pagx/html/HTMLWriter.h"
#include "pagx/utils/StringParser.h"

namespace pagx {

//==============================================================================
// Coordinate rounding
//==============================================================================

// Rounds every <number>px in a CSS style fragment to at most two decimal places. Matching on
// the `px` suffix keeps transform matrix components, color channels, rotation angles (deg),
// scale factors, and SVG path data untouched.
static std::string RoundPxInStyle(const std::string& style) {
  std::string result;
  result.reserve(style.size());
  size_t i = 0;
  while (i < style.size()) {
    char c = style[i];
    bool isDigitStart = (c >= '0' && c <= '9') || c == '.';
    bool isSignedDigit = (c == '-' || c == '+') && i + 1 < style.size() &&
                         ((style[i + 1] >= '0' && style[i + 1] <= '9') || style[i + 1] == '.');
    if (!isDigitStart && !isSignedDigit) {
      result += c;
      i++;
      continue;
    }

    size_t numStart = i;
    size_t j = i;
    if (style[j] == '-' || style[j] == '+') {
      j++;
    }
    bool sawDigit = false;
    bool sawDot = false;
    while (j < style.size()) {
      char cj = style[j];
      if (cj >= '0' && cj <= '9') {
        sawDigit = true;
        j++;
      } else if (cj == '.' && !sawDot) {
        sawDot = true;
        j++;
      } else {
        break;
      }
    }

    if (!sawDigit || j + 1 >= style.size() || style[j] != 'p' || style[j + 1] != 'x') {
      result += style.substr(numStart, j - numStart);
      i = j;
      continue;
    }

    std::string numStr = style.substr(numStart, j - numStart);
    float value = static_cast<float>(std::atof(numStr.c_str()));
    auto rounded = CoordToString(value);
    result += rounded;
    if (rounded != "0") {
      result += "px";
    }
    i = j + 2;
  }
  return result;
}

// Walks the generated HTML, finds every `style="..."` attribute, and applies RoundPxInStyle
// to its contents. Leaves <script> bodies, SVG path data, transform matrix components, and
// every attribute other than style untouched.
static std::string RoundCoordinatesInHTML(const std::string& html) {
  std::string result;
  result.reserve(html.size());
  size_t pos = 0;
  while (pos < html.size()) {
    size_t stylePos = html.find("style=\"", pos);
    if (stylePos == std::string::npos) {
      result += html.substr(pos);
      break;
    }
    result += html.substr(pos, stylePos - pos);
    size_t valueStart = stylePos + 7;
    size_t valueEnd = html.find('"', valueStart);
    if (valueEnd == std::string::npos) {
      result += html.substr(stylePos);
      break;
    }
    std::string styleValue = html.substr(valueStart, valueEnd - valueStart);
    result += "style=\"";
    result += RoundPxInStyle(styleValue);
    result += "\"";
    pos = valueEnd + 1;
  }
  return result;
}

//==============================================================================
// ToHTML / ToFile
//==============================================================================

static constexpr const char* GENERATED_COMMENT =
    "<!-- Generated by PAGX HTMLExporter. Do not edit. -->\n";

static std::string WrapAsHTMLDocument(const std::string& fragment, float width, float height) {
  auto w = std::to_string(static_cast<int>(width));
  auto h = std::to_string(static_cast<int>(height));
  std::string bodyStyle = "margin:0;padding:0;width:" + w + "px;height:" + h +
                          "px;overflow:hidden;font-family:sans-serif";
  return "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<style>\nbody { " + bodyStyle +
         " }\n</style>\n</head>\n<body>\n" + fragment + "\n</body>\n</html>\n";
}

std::string HTMLExporter::ToHTML(PAGXDocument& doc, const std::string& resourceDir,
                                 const Options& options, std::string* errorMsg) {
  if (resourceDir.empty()) {
    if (errorMsg) {
      *errorMsg = "resourceDir must not be empty.";
    }
    std::cerr << "HTMLExporter::ToHTML: resourceDir must not be empty. "
                 "Use HTMLExporter::ToFile for automatic resource-directory derivation."
              << std::endl;
    return {};
  }
  if (!std::filesystem::path(resourceDir).is_absolute()) {
    if (errorMsg) {
      *errorMsg = "resourceDir must be an absolute path, got '" + resourceDir + "'.";
    }
    std::cerr << "HTMLExporter::ToHTML: resourceDir must be an absolute path, got '" << resourceDir
              << "'." << std::endl;
    return {};
  }
  if (!doc.isLayoutApplied()) {
    doc.applyLayout();
  }
  // Derive the URL prefix used by <img src=...> from the resource directory's basename. This
  // assumes the caller will write the returned HTML string to a file located in resourceDir's
  // parent directory (ToFile enforces this layout automatically).
  auto resourceDirPath = std::filesystem::path(resourceDir);
  std::string urlPrefix = resourceDirPath.filename().string();
  if (!urlPrefix.empty()) {
    urlPrefix += '/';
  }

  HTMLBuilder html(0, 4096);
  HTMLBuilder defs(2, 4096);
  HTMLWriterContext ctx;
  ctx.docWidth = doc.width;
  ctx.docHeight = doc.height;
  ctx.staticImgDir = resourceDir;
  ctx.staticImgUrlPrefix = urlPrefix;
  ctx.rasterScale = std::clamp(options.rasterScale, 0.01f, 4.0f);

  // Pre-pass: for every compatible PlusDarker Layer, render a cropped backdrop PNG with the layer
  // temporarily hidden. The resulting base64 data URLs are consumed by writeLayer below to emit an
  // SVG filter (feImage + feComposite arithmetic) that matches tgfx PlusDarker pixel-for-pixel.
  HTMLPlusDarkerRenderer::RenderAll(doc, resourceDir, urlPrefix, options.rasterScale,
                                    ctx.plusDarkerBackdrops);

  HTMLWriter writer(&defs, &ctx);

  // Root div
  std::string rootStyle = "position:relative;width:" + CssFloatToString(doc.width) +
                          "px;height:" + CssFloatToString(doc.height) + "px;overflow:hidden";
  html.openTag("div");
  html.addAttr("data-pagx-version", "1.0");
  html.addAttr("style", rootStyle);
  html.closeTagStart();

  // Render layers into body content
  HTMLBuilder body(1, 4096);
  for (auto* layer : doc.layers) {
    writer.writeLayer(body, layer);
  }

  // Insert SVG defs if any
  std::string defsStr = defs.release();
  if (!defsStr.empty()) {
    html.openTag("svg");
    html.addAttr("style", "position:absolute;width:0;height:0;overflow:hidden");
    html.closeTagStart();
    html.openTag("defs");
    html.closeTagStart();
    html.addRawContent(defsStr);
    html.closeTag();  // </defs>
    html.closeTag();  // </svg>
  }

  html.addRawContent(body.release());

  html.closeTag();  // </div>

  std::string nativeHTML = RoundCoordinatesInHTML(html.release());

  if (options.extractStyleSheet) {
    nativeHTML = HTMLStyleExtractor::Extract(nativeHTML);
  }

  std::string result = std::string(GENERATED_COMMENT) + nativeHTML;

  // wrapFullDocument: -1 = per-method default (false for ToHTML), 0 = false, 1 = true
  bool wrap = options.wrapFullDocument > 0;
  if (wrap) {
    result = WrapAsHTMLDocument(result, doc.width, doc.height);
  }

  return result;
}

bool HTMLExporter::ToFile(PAGXDocument& document, const std::string& filePath,
                          const Options& options, std::string* errorMsg) {
  // Derive the resource directory as a sibling of the HTML file named after its stem:
  // "/tmp/abc.html" → resourceDir = "/tmp/abc".
  auto htmlPath = std::filesystem::path(filePath);
  auto stem = htmlPath.stem().string();
  if (stem.empty()) {
    if (errorMsg) {
      *errorMsg = "filePath must have a non-empty stem: " + filePath;
    }
    std::cerr << "HTMLExporter::ToFile: filePath must have a non-empty stem: " << filePath
              << std::endl;
    return false;
  }
  auto parentDir = htmlPath.parent_path();
  auto resourceDir = (parentDir.empty() ? std::filesystem::path(".") : parentDir) / stem;

  // ToFile defaults to wrapping as a full HTML document unless explicitly disabled.
  Options toFileOptions = options;
  if (toFileOptions.wrapFullDocument < 0) {
    toFileOptions.wrapFullDocument = 1;
  }

  auto html = ToHTML(document, resourceDir.string(), toFileOptions, errorMsg);
  if (html.empty()) {
    return false;
  }
  if (!parentDir.empty() && !std::filesystem::exists(parentDir)) {
    std::error_code ec = {};
    std::filesystem::create_directories(parentDir, ec);
    if (ec) {
      if (errorMsg) {
        *errorMsg = "failed to create directory: " + parentDir.string();
      }
      return false;
    }
  }
  std::ofstream file(filePath, std::ios::binary);
  if (!file) {
    if (errorMsg) {
      *errorMsg = "failed to write file: " + filePath;
    }
    return false;
  }
  file.write(html.data(), static_cast<std::streamsize>(html.size()));
  return file.good();
}

}  // namespace pagx
