/////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Tencent is pleased to support the open source community by making libpag available.
//
//  Copyright (C) 2026 Tencent. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  unless required by applicable law or agreed to in writing, software distributed under the
//  license is distributed on an "as is" basis, without warranties or conditions of any kind,
//  either express or implied. see the license for the specific language governing permissions
//  and limitations under the license.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

#include "pagx/HTMLExporter.h"
#include <cctype>
#include <filesystem>
#include <fstream>
#include <string>
#include <unordered_map>
#include "pagx/html/HTMLBuilder.h"
#include "pagx/html/HTMLWriter.h"
#include "pagx/utils/StringParser.h"

namespace pagx {

//==============================================================================
// Framework Serializers
//==============================================================================

static constexpr const char* kGeneratedCommentNative =
    "<!-- Generated by PAGX HTMLExporter. Do not edit. -->\n";
static constexpr const char* kGeneratedCommentJS =
    "// Generated by PAGX HTMLExporter. Do not edit.\n";

static std::string KebabToCamelCase(const std::string& kebab) {
  std::string result;
  result.reserve(kebab.size());
  bool capitalizeNext = false;
  bool isVendorPrefix = !kebab.empty() && kebab[0] == '-';

  for (size_t i = 0; i < kebab.size(); i++) {
    char c = kebab[i];
    if (c == '-') {
      capitalizeNext = true;
      continue;
    }
    if (capitalizeNext) {
      result += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
      capitalizeNext = false;
    } else {
      result += c;
    }
  }

  if (isVendorPrefix && !result.empty()) {
    result[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(result[0])));
  }

  return result;
}

static bool IsNumericValue(const std::string& value) {
  if (value.empty()) {
    return false;
  }
  size_t i = 0;
  bool hasDot = false;
  bool hasDigit = false;

  if (value[i] == '-' || value[i] == '+') {
    i++;
  }

  while (i < value.size()) {
    char c = value[i];
    if (c >= '0' && c <= '9') {
      hasDigit = true;
      i++;
    } else if (c == '.' && !hasDot) {
      hasDot = true;
      i++;
    } else {
      return false;
    }
  }
  return hasDigit;
}

static std::string StyleStringToJSXObject(const std::string& styleStr) {
  if (styleStr.empty()) {
    return "{}";
  }

  std::string result = "{";
  size_t pos = 0;
  bool first = true;

  while (pos < styleStr.size()) {
    size_t semicolonPos = styleStr.find(';', pos);
    if (semicolonPos == std::string::npos) {
      semicolonPos = styleStr.size();
    }

    std::string pair = styleStr.substr(pos, semicolonPos - pos);
    pos = semicolonPos + 1;

    if (pair.empty()) {
      continue;
    }

    auto colonPos = pair.find(':');
    if (colonPos == std::string::npos) {
      continue;
    }

    std::string key = pair.substr(0, colonPos);
    std::string value = pair.substr(colonPos + 1);

    while (!key.empty() && key[0] == ' ') {
      key = key.substr(1);
    }
    while (!key.empty() && key.back() == ' ') {
      key.pop_back();
    }
    while (!value.empty() && value[0] == ' ') {
      value = value.substr(1);
    }
    while (!value.empty() && value.back() == ' ') {
      value.pop_back();
    }

    if (key.empty()) {
      continue;
    }

    if (!first) {
      result += ", ";
    }
    first = false;

    std::string camelKey = KebabToCamelCase(key);
    result += camelKey + ": ";

    if (IsNumericValue(value)) {
      result += value;
    } else {
      // Escape double quotes in value for JSX style object
      std::string escaped = value;
      for (size_t p = 0; p < escaped.size(); p++) {
        if (escaped[p] == '"') {
          escaped.replace(p, 1, "\\\"");
          p++;
        }
      }
      result += "\"" + escaped + "\"";
    }
  }

  result += "}";
  return result;
}

static std::string StyleStringToVueObject(const std::string& styleStr) {
  if (styleStr.empty()) {
    return "{}";
  }

  std::string result = "{";
  size_t pos = 0;
  bool first = true;

  while (pos < styleStr.size()) {
    size_t semicolonPos = styleStr.find(';', pos);
    if (semicolonPos == std::string::npos) {
      semicolonPos = styleStr.size();
    }

    std::string pair = styleStr.substr(pos, semicolonPos - pos);
    pos = semicolonPos + 1;

    if (pair.empty()) {
      continue;
    }

    auto colonPos = pair.find(':');
    if (colonPos == std::string::npos) {
      continue;
    }

    std::string key = pair.substr(0, colonPos);
    std::string value = pair.substr(colonPos + 1);

    while (!key.empty() && key[0] == ' ') {
      key = key.substr(1);
    }
    while (!key.empty() && key.back() == ' ') {
      key.pop_back();
    }
    while (!value.empty() && value[0] == ' ') {
      value = value.substr(1);
    }
    while (!value.empty() && value.back() == ' ') {
      value.pop_back();
    }

    if (key.empty()) {
      continue;
    }

    if (!first) {
      result += ", ";
    }
    first = false;

    std::string camelKey = KebabToCamelCase(key);
    result += camelKey + ": ";

    if (IsNumericValue(value)) {
      result += value;
    } else {
      // Escape single quotes in value for Vue style object
      std::string escaped = value;
      for (size_t p = 0; p < escaped.size(); p++) {
        if (escaped[p] == '\'') {
          escaped.replace(p, 1, "\\\'");
          p++;
        }
      }
      result += "'" + escaped + "'";
    }
  }

  result += "}";
  return result;
}

// Decode HTML entities back to raw characters before style parsing.
// This is necessary because escapeAttr() encodes quotes (&#39; &quot;) which
// contain semicolons that would be misinterpreted as CSS property separators.
static std::string DecodeHTMLEntities(const std::string& str) {
  std::string result;
  result.reserve(str.size());
  size_t i = 0;
  while (i < str.size()) {
    if (str[i] == '&') {
      if (str.compare(i, 5, "&#39;") == 0) {
        result += '\'';
        i += 5;
      } else if (str.compare(i, 6, "&quot;") == 0) {
        result += '"';
        i += 6;
      } else if (str.compare(i, 5, "&amp;") == 0) {
        result += '&';
        i += 5;
      } else if (str.compare(i, 4, "&lt;") == 0) {
        result += '<';
        i += 4;
      } else if (str.compare(i, 4, "&gt;") == 0) {
        result += '>';
        i += 4;
      } else {
        result += str[i++];
      }
    } else {
      result += str[i++];
    }
  }
  return result;
}

static std::string TransformStyleAttributes(const std::string& html, bool useDoubleQuotes) {
  std::string result;
  result.reserve(html.size() * 2);
  size_t pos = 0;

  while (pos < html.size()) {
    size_t stylePos = html.find("style=\"", pos);
    if (stylePos == std::string::npos) {
      result += html.substr(pos);
      break;
    }

    result += html.substr(pos, stylePos - pos);

    size_t valueStart = stylePos + 7;
    size_t valueEnd = html.find('"', valueStart);
    if (valueEnd == std::string::npos) {
      result += html.substr(stylePos);
      break;
    }

    std::string styleValue = DecodeHTMLEntities(html.substr(valueStart, valueEnd - valueStart));
    std::string styleObj =
        useDoubleQuotes ? StyleStringToJSXObject(styleValue) : StyleStringToVueObject(styleValue);

    if (useDoubleQuotes) {
      result += "style={" + styleObj + "}";
    } else {
      result += ":style=\"" + styleObj + "\"";
    }

    pos = valueEnd + 1;
  }

  return result;
}

static std::string ReplaceClassWithClassName(const std::string& html) {
  std::string result;
  result.reserve(html.size());
  size_t pos = 0;

  while (pos < html.size()) {
    size_t classPos = html.find("class=\"", pos);
    if (classPos == std::string::npos) {
      result += html.substr(pos);
      break;
    }

    if (classPos > 0) {
      char prevChar = html[classPos - 1];
      if (prevChar != ' ' && prevChar != '\n' && prevChar != '\t' && prevChar != '<') {
        result += html.substr(pos, classPos - pos + 6);
        pos = classPos + 6;
        continue;
      }
    }

    result += html.substr(pos, classPos - pos);
    result += "className=\"";
    pos = classPos + 7;
  }

  return result;
}

static std::string ReplaceHTMLComments(const std::string& html) {
  std::string result;
  result.reserve(html.size());
  size_t pos = 0;

  while (pos < html.size()) {
    size_t commentStart = html.find("<!--", pos);
    if (commentStart == std::string::npos) {
      result += html.substr(pos);
      break;
    }

    result += html.substr(pos, commentStart - pos);

    size_t commentEnd = html.find("-->", commentStart);
    if (commentEnd == std::string::npos) {
      result += html.substr(commentStart);
      break;
    }

    std::string commentContent = html.substr(commentStart + 4, commentEnd - commentStart - 4);
    result += "{/*" + commentContent + "*/}";
    pos = commentEnd + 3;
  }

  return result;
}

// Rewrites kebab-case SVG attribute names to the camelCase form React/JSX expects. React
// treats DOM attributes as React props and only recognises the camelCase spelling for SVG
// presentation attributes (stop-color → stopColor etc.); kebab-case would be dropped with a
// "Invalid DOM property" warning and the visual (dashes, gradient stops, stroke widths...)
// would disappear. The transform preserves data-* and aria-* attributes, which React allows
// in their dashed form.
static std::string TransformSVGAttributeNames(const std::string& jsx) {
  static const std::unordered_map<std::string, std::string> kKebabToCamel = {
      {"clip-path", "clipPath"},
      {"clip-rule", "clipRule"},
      {"color-interpolation-filters", "colorInterpolationFilters"},
      {"fill-opacity", "fillOpacity"},
      {"fill-rule", "fillRule"},
      {"flood-color", "floodColor"},
      {"flood-opacity", "floodOpacity"},
      {"stop-color", "stopColor"},
      {"stop-opacity", "stopOpacity"},
      {"stroke-dasharray", "strokeDasharray"},
      {"stroke-dashoffset", "strokeDashoffset"},
      {"stroke-linecap", "strokeLinecap"},
      {"stroke-linejoin", "strokeLinejoin"},
      {"stroke-miterlimit", "strokeMiterlimit"},
      {"stroke-opacity", "strokeOpacity"},
      {"stroke-width", "strokeWidth"},
      {"text-anchor", "textAnchor"},
      {"dominant-baseline", "dominantBaseline"},
      {"alignment-baseline", "alignmentBaseline"},
      {"gradient-units", "gradientUnits"},
      {"gradient-transform", "gradientTransform"},
      {"pattern-units", "patternUnits"},
      {"pattern-content-units", "patternContentUnits"},
      {"pattern-transform", "patternTransform"},
  };

  std::string result;
  result.reserve(jsx.size());
  size_t pos = 0;
  while (pos < jsx.size()) {
    char c = jsx[pos];
    if (c != '<') {
      result += c;
      pos++;
      continue;
    }

    size_t tagClose = jsx.find('>', pos);
    if (tagClose == std::string::npos) {
      result += jsx.substr(pos);
      break;
    }

    // Skip comment/CDATA/processing-instruction tokens that just happen to start with '<'.
    if (pos + 1 < jsx.size() && (jsx[pos + 1] == '!' || jsx[pos + 1] == '?')) {
      result += jsx.substr(pos, tagClose - pos + 1);
      pos = tagClose + 1;
      continue;
    }

    std::string tagContent = jsx.substr(pos, tagClose - pos + 1);
    std::string rewritten;
    rewritten.reserve(tagContent.size());
    size_t i = 0;
    while (i < tagContent.size()) {
      char ch = tagContent[i];
      // Attribute names begin after whitespace and are terminated by '=' or whitespace or '>'.
      // Names always start with a letter; look for kebab identifiers and rewrite if matched.
      if ((ch == ' ' || ch == '\t' || ch == '\n') && i + 1 < tagContent.size() &&
          (std::isalpha(static_cast<unsigned char>(tagContent[i + 1])) ||
           tagContent[i + 1] == '-')) {
        rewritten += ch;
        i++;
        size_t nameStart = i;
        while (i < tagContent.size()) {
          char nc = tagContent[i];
          if (std::isalnum(static_cast<unsigned char>(nc)) || nc == '-' || nc == '_' || nc == ':') {
            i++;
          } else {
            break;
          }
        }
        std::string name = tagContent.substr(nameStart, i - nameStart);
        auto it = kKebabToCamel.find(name);
        if (it != kKebabToCamel.end()) {
          rewritten += it->second;
        } else {
          rewritten += name;
        }
        continue;
      }
      rewritten += ch;
      i++;
    }

    result += rewritten;
    pos = tagClose + 1;
  }
  return result;
}

static std::string SerializeToReactJSX(const std::string& nativeHTML,
                                       const HTMLExportOptions& options) {
  std::string jsx = nativeHTML;

  jsx = ReplaceClassWithClassName(jsx);
  jsx = ReplaceHTMLComments(jsx);
  jsx = TransformSVGAttributeNames(jsx);
  jsx = TransformStyleAttributes(jsx, true);

  std::string indentStr(static_cast<size_t>(options.indent * 2), ' ');
  std::string singleIndent(static_cast<size_t>(options.indent), ' ');

  std::string result;
  result.reserve(jsx.size() + 400);
  result += kGeneratedCommentJS;
  result += "export default function " + options.componentName + "() {\n";
  result += singleIndent + "return (\n";

  size_t lineStart = 0;
  while (lineStart < jsx.size()) {
    size_t lineEnd = jsx.find('\n', lineStart);
    if (lineEnd == std::string::npos) {
      lineEnd = jsx.size();
    }

    std::string line = jsx.substr(lineStart, lineEnd - lineStart);
    result += indentStr + line + "\n";
    lineStart = lineEnd + 1;
  }

  result += singleIndent + ");\n";
  result += "}\n";

  return result;
}

static std::string SerializeToVueSFC(const std::string& nativeHTML,
                                     const HTMLExportOptions& options) {
  std::string vue = TransformStyleAttributes(nativeHTML, false);

  std::string singleIndent(static_cast<size_t>(options.indent), ' ');

  std::string result;
  result.reserve(vue.size() + 400);
  result += "<!-- Generated by PAGX HTMLExporter. Do not edit. -->\n";
  result += "<template>\n";

  size_t lineStart = 0;
  while (lineStart < vue.size()) {
    size_t lineEnd = vue.find('\n', lineStart);
    if (lineEnd == std::string::npos) {
      lineEnd = vue.size();
    }

    std::string line = vue.substr(lineStart, lineEnd - lineStart);
    result += singleIndent + line + "\n";
    lineStart = lineEnd + 1;
  }

  result += "</template>\n\n";
  result += "<script setup>\n";
  result += "// No setup logic required for this component.\n";
  result += "</script>\n";

  return result;
}

//==============================================================================
// Coordinate rounding
//==============================================================================

// Rounds every <number>px in a CSS style fragment to at most two decimal places. Matching on
// the `px` suffix keeps transform matrix components, color channels, rotation angles (deg),
// scale factors, and SVG path data untouched.
static std::string RoundPxInStyle(const std::string& style) {
  std::string result;
  result.reserve(style.size());
  size_t i = 0;
  while (i < style.size()) {
    char c = style[i];
    bool isDigitStart = (c >= '0' && c <= '9') || c == '.';
    bool isSignedDigit = (c == '-' || c == '+') && i + 1 < style.size() &&
                         ((style[i + 1] >= '0' && style[i + 1] <= '9') || style[i + 1] == '.');
    if (!isDigitStart && !isSignedDigit) {
      result += c;
      i++;
      continue;
    }

    size_t numStart = i;
    size_t j = i;
    if (style[j] == '-' || style[j] == '+') {
      j++;
    }
    bool sawDigit = false;
    bool sawDot = false;
    while (j < style.size()) {
      char cj = style[j];
      if (cj >= '0' && cj <= '9') {
        sawDigit = true;
        j++;
      } else if (cj == '.' && !sawDot) {
        sawDot = true;
        j++;
      } else {
        break;
      }
    }

    if (!sawDigit || j + 1 >= style.size() || style[j] != 'p' || style[j + 1] != 'x') {
      result += style.substr(numStart, j - numStart);
      i = j;
      continue;
    }

    std::string numStr = style.substr(numStart, j - numStart);
    float value = static_cast<float>(std::atof(numStr.c_str()));
    result += CoordToString(value);
    result += "px";
    i = j + 2;
  }
  return result;
}

// Walks the generated HTML, finds every `style="..."` attribute, and applies RoundPxInStyle
// to its contents. Leaves <script> bodies, SVG path data, transform matrix components, and
// every attribute other than style untouched.
static std::string RoundCoordinatesInHTML(const std::string& html) {
  std::string result;
  result.reserve(html.size());
  size_t pos = 0;
  while (pos < html.size()) {
    size_t stylePos = html.find("style=\"", pos);
    if (stylePos == std::string::npos) {
      result += html.substr(pos);
      break;
    }
    result += html.substr(pos, stylePos - pos);
    size_t valueStart = stylePos + 7;
    size_t valueEnd = html.find('"', valueStart);
    if (valueEnd == std::string::npos) {
      result += html.substr(stylePos);
      break;
    }
    std::string styleValue = html.substr(valueStart, valueEnd - valueStart);
    result += "style=\"";
    result += RoundPxInStyle(styleValue);
    result += "\"";
    pos = valueEnd + 1;
  }
  return result;
}

//==============================================================================
// File header
//==============================================================================

std::string HTMLExporter::ToHTML(const PAGXDocument& doc, const Options& options) {
  HTMLBuilder html(options.indent);
  HTMLBuilder defs(options.indent, 2);
  HTMLWriterContext ctx;
  ctx.docWidth = doc.width;
  ctx.docHeight = doc.height;
  ctx.staticImgDir = options.staticImgDir;
  ctx.staticImgUrlPrefix = options.staticImgUrlPrefix;
  ctx.staticImgNamePrefix = options.staticImgNamePrefix;
  ctx.staticImgPixelRatio = options.staticImgPixelRatio;
  HTMLWriter writer(&defs, &ctx);

  // Root div
  std::string rootStyle = "position:relative;width:" + FloatToString(doc.width) +
                          "px;height:" + FloatToString(doc.height) + "px;overflow:hidden";
  html.openTag("div");
  html.addAttr("class", "pagx-root");
  html.addAttr("data-pagx-version", "1.0");
  html.addAttr("style", rootStyle);
  html.closeTagStart();

  // Render layers into body content
  HTMLBuilder body(options.indent, 1);
  for (auto* layer : doc.layers) {
    writer.writeLayer(body, layer);
  }

  // Insert SVG defs if any
  std::string defsStr = defs.release();
  if (!defsStr.empty()) {
    html.openTag("svg");
    html.addAttr("style", "position:absolute;width:0;height:0;overflow:hidden");
    html.closeTagStart();
    html.openTag("defs");
    html.closeTagStart();
    html.addRawContent(defsStr);
    html.closeTag();  // </defs>
    html.closeTag();  // </svg>
  }

  html.addRawContent(body.release());

  html.closeTag();  // </div>

  std::string nativeHTML = RoundCoordinatesInHTML(html.release());

  // Apply framework-specific transformation
  switch (options.framework) {
    case HTMLFramework::React:
      return SerializeToReactJSX(nativeHTML, options);
    case HTMLFramework::Vue:
      return SerializeToVueSFC(nativeHTML, options);
    case HTMLFramework::Native:
    default:
      return std::string(kGeneratedCommentNative) + nativeHTML;
  }
}

bool HTMLExporter::ToFile(const PAGXDocument& document, const std::string& filePath,
                          const Options& options) {
  auto html = ToHTML(document, options);
  if (html.empty()) {
    return false;
  }
  auto dirPath = std::filesystem::path(filePath).parent_path();
  if (!dirPath.empty() && !std::filesystem::exists(dirPath)) {
    std::error_code ec = {};
    std::filesystem::create_directories(dirPath, ec);
    if (ec) {
      return false;
    }
  }
  std::ofstream file(filePath, std::ios::binary);
  if (!file) {
    return false;
  }
  file.write(html.data(), static_cast<std::streamsize>(html.size()));
  return file.good();
}

}  // namespace pagx
