#!/bin/bash

# Build script for PAGX Chrome Extension
# This script builds the WASM module, copies runtime assets (fonts, WASM),
# and bundles viewer.ts into viewer.js.
#
# All build outputs (wasm/, fonts/, viewer/viewer.js) are gitignored and
# must be regenerated by running this script after a fresh clone.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo "Building PAGX Chrome Extension..."

# Step 1: Build WASM module using playground build system
echo "Step 1: Building WASM module..."
cd "${PROJECT_ROOT}/playground"
npm run build:release

# Step 2: Copy WASM artifacts
echo "Step 2: Copying WASM artifacts..."
WASM_SRC="${PROJECT_ROOT}/playground/wasm-mt"
WASM_DST="${SCRIPT_DIR}/wasm"
mkdir -p "${WASM_DST}"
cp "${WASM_SRC}/pagx-playground.js" "${WASM_DST}/"
cp "${WASM_SRC}/pagx-playground.wasm" "${WASM_DST}/"
if [ -f "${WASM_SRC}/pagx-playground.worker.js" ]; then
  cp "${WASM_SRC}/pagx-playground.worker.js" "${WASM_DST}/"
fi

# Step 3: Copy fonts from project resources
echo "Step 3: Copying fonts..."
FONT_SRC="${PROJECT_ROOT}/resources/font"
FONT_DST="${SCRIPT_DIR}/fonts"
mkdir -p "${FONT_DST}"
cp "${FONT_SRC}/NotoSansSC-Regular.otf" "${FONT_DST}/"
cp "${FONT_SRC}/NotoColorEmoji.ttf" "${FONT_DST}/"

# Step 4: Install dependencies and build viewer.js
echo "Step 4: Building viewer.js..."
cd "${SCRIPT_DIR}"
npm install
npm run build

echo ""
echo "Build complete! Extension ready at: ${SCRIPT_DIR}"
echo ""
echo "To load the extension in Chrome:"
echo "  1. Open chrome://extensions"
echo "  2. Enable 'Developer mode' (top right)"
echo "  3. Click 'Load unpacked' and select: ${SCRIPT_DIR}"
echo ""
echo "Note: You may need to enable 'Allow access to file URLs' in the extension details."
