# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'
ENV["PLATFORM"] = "mac"
install! 'cocoapods', :deterministic_uuids => false

target 'PAGViewer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for PAGViewer
    pod 'libpag', :path => '../'
end
