export const enum CompositionType {
  Unknown,
  Vector,
  Bitmap,
  Video,
}

export const enum TagCode {
  End = 0,
  FontTables = 1,
  VectorCompositionBlock = 2,
  CompositionAttributes = 3,
  ImageTables = 4,
  LayerBlock = 5,
  LayerAttributes = 6,
  SolidColor = 7,
  TextSource = 8,
  TextPathOption = 9,
  TextMoreOption = 10,
  ImageReference = 11,
  CompositionReference = 12,
  Transform2D = 13,
  MaskBlock = 14,
  ShapeGroup = 15,
  Rectangle = 16,
  Ellipse = 17,
  PolyStar = 18,
  ShapePath = 19,
  Fill = 20,
  Stroke = 21,
  GradientFill = 22,
  GradientStroke = 23,
  MergePaths = 24,
  TrimPaths = 25,
  Repeater = 26,
  RoundCorners = 27,
  Performance = 28,
  DropShadowStyle = 29,
  InnerShadowStyle = 30,
  OuterGlowStyle = 31,
  InnerGlowStyle = 32,
  BevelAndEmbossStyle = 33,
  SatinStyle = 34,
  ColorOverlayStyle = 35,
  GradientOverlayStyle = 36,
  StrokeStyle = 37,
  TintEffect = 38,
  FillEffect = 39,
  StrokeEffect = 40,
  TritoneEffect = 41,
  DropShadowEffect = 42,
  RadialWipeEffect = 43,
  DisplacementMapEffect = 44,
  BitmapCompositionBlock = 45,
  BitmapSequence = 46,
  ImageBytes = 47,
  ImageBytes2 = 48,
  ImageBytes3 = 49,
  VideoCompositionBlock = 50,
  VideoSequence = 51,
  LayerAttributesV2 = 52,
  // add new tags here...
  Count,
}
