#!/usr/bin/env node
process.chdir(__dirname);

const childProcess = require("child_process");
childProcess.execSync("depsync");

process.argv.push("../");
process.argv.push("-w");
let args = process.argv.slice(2);
if (args.indexOf("-p") === -1 && args.indexOf("--platform") === -1) {
    process.argv.push("-p");
    process.argv.push("ios");
}
require("../third_party/vendor_tools/xcode-gen");
