# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
ENV["PLATFORM"] = "ios"
install! 'cocoapods', :deterministic_uuids => false

targetsArray = ['PAGViewer', 'PAGViewerTest']

targetsArray.each do |t|
  target t do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for PAGViewer
    pod 'libpag', :path => '../'
  end
end
