/////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Tencent is pleased to support the open source community by making libpag available.
//
//  Copyright (C) 2026 Tencent. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  unless required by applicable law or agreed to in writing, software distributed under the
//  license is distributed on an "as is" basis, without warranties or conditions of any kind,
//  either express or implied. see the license for the specific language governing permissions
//  and limitations under the license.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <string>
#include "pagx/PAGXDocument.h"

namespace pagx {

/**
 * Output formatting style for the generated HTML document.
 */
enum class HTMLFormat {
  /**
   * Balanced format intended for development and diff-friendly inspection.
   * - HTML: tags are newline-separated and indented by `HTMLExportOptions::indent` spaces per
   *   nesting level.
   * - CSS: inside the <style> block, each rule sits on its own line, but the declarations of
   *   any single rule are concatenated on that same line (`selector{a:x;b:y}`) with no
   *   per-declaration indent.
   * - Includes the "Generated by" head comment.
   * Moderate file size — larger than Minify, smaller than Pretty. Good default for CI and
   * debugging where round-tripping through text diff tools matters.
   */
  Compact,

  /**
   * Maximally readable format intended for hand-editing and debugging.
   * - HTML: tags are newline-separated and indented by `HTMLExportOptions::indent` spaces per
   *   nesting level (identical to Compact).
   * - CSS: inside the <style> block, each declaration sits on its own line with a fixed
   *   2-space indent beneath its selector.
   * - Includes the "Generated by" head comment.
   * Produces the largest file of the three modes; pick this when a human will read the HTML.
   */
  Pretty,

  /**
   * Size-optimised format intended for production delivery.
   * - HTML: no newlines, no indentation — the entire document is a single line.
   * - CSS: the entire <style> block is collapsed onto one line, with every rule and
   *   declaration concatenated without whitespace separators.
   * - Omits the "Generated by" head comment.
   * Produces the smallest file of the three modes; the `HTMLExportOptions::indent` field is
   * ignored in this mode.
   */
  Minify,
};

/**
 * Export options for HTMLExporter.
 */
struct HTMLExportOptions {
  /**
   * Output formatting style for the HTML document. The default is Pretty,
   * which emits each CSS declaration on its own indented line for readability.
   */
  HTMLFormat format = HTMLFormat::Pretty;

  /**
   * Indentation width (in space characters) applied to HTML tag nesting in the output. The
   * default is 2. This value only affects the indentation of <tag>...</tag> nesting levels
   * produced by the HTML builder; it does not influence the formatting of CSS declarations
   * inside the <style> block — Compact mode always writes declarations on a single line per
   * rule, and Pretty mode always uses a fixed 2-space declaration indent regardless of this
   * value. Ignored entirely when `format` is HTMLFormat::Minify. Negative values are not
   * defined; callers should pass a non-negative integer.
   */
  int indent = 2;

  /**
   * Absolute directory path where the exporter writes PNG files for shapes filled with color
   * sources that CSS cannot express natively (DiamondGradient and tiled ImagePattern). The
   * exporter creates the directory if it does not exist. When left empty, such shapes are
   * silently skipped in the HTML output.
   */
  std::string staticImgDir = {};

  /**
   * URL prefix used for <img src="..."> references to the generated static images, relative to
   * the HTML document's location. The default is "static-img/", matching the convention that
   * static-img/ sits next to the HTML file.
   */
  std::string staticImgUrlPrefix = "static-img/";

  /**
   * Filename prefix applied to every generated static image, useful when multiple HTML documents
   * share a single static-img directory and need to avoid name collisions (e.g., "doc_name-").
   */
  std::string staticImgNamePrefix = {};

  /**
   * Device pixel ratio used when rasterizing static images. A value of 2 produces @2x assets,
   * which keeps visual parity with the browser's 2x comparison output. The default is 2.
   */
  float staticImgPixelRatio = 2.0f;

  /**
   * When true, all inline `style="..."` attributes are consolidated into a
   * single internal stylesheet placed in the document <head>, and elements
   * reference styles via generated class names (`.ps0`, `.ps1`, ...). This
   * typically reduces HTML size by 10-25% for documents with repeated style
   * declarations. When false, every style remains inline.
   *
   * The document's <body> `style` attribute is always kept inline because it
   * is unique per document and gains nothing from extraction.
   *
   * The default is true.
   */
  bool extractStyleSheet = true;
};

/**
 * HTMLExporter converts a PAGXDocument into HTML/CSS/SVG format.
 * The output is a standalone HTML fragment that renders the PAGX content visually
 * equivalent to the native PAGX renderer in modern browsers.
 */
class HTMLExporter {
 public:
  using Options = HTMLExportOptions;

  /**
   * Exports a PAGXDocument to an HTML string. The output is a standalone HTML fragment containing
   * CSS styles and SVG elements that visually reproduce the PAGX content in modern browsers.
   *
   * Thread safety: this is a stateless static method and may be called concurrently from
   * multiple threads, provided that each thread passes a distinct document (or a document that
   * is guaranteed not to be mutated for the duration of the call).
   *
   * Failure semantics: returns an empty string both on internal failure and when the document
   * genuinely has no visible content. The two cases are not distinguished by the return value;
   * callers that need to tell them apart should inspect the document themselves (for example,
   * check that `document` has a non-null root layer) before invoking ToHTML.
   *
   * Ownership: `document` is consumed by const reference. The exporter does not retain any
   * pointer or reference to the document or its internal nodes beyond the duration of this
   * call, so the caller is free to destroy or mutate `document` as soon as ToHTML returns.
   *
   * @param document The PAGX document to export.
   * @param options Export options controlling output formatting.
   * @return The generated HTML string, or an empty string if the document has no content or
   *         if the exporter encountered an internal failure.
   */
  static std::string ToHTML(const PAGXDocument& document, const Options& options = {});

  /**
   * Exports a PAGXDocument to an HTML file. Creates parent directories if they do not exist.
   *
   * File handling: the output file is opened with std::ios::binary and truncated; if a file
   * already exists at `filePath` it is overwritten without prompting. `filePath` is used
   * verbatim — the library does not validate, sanitise, or restrict it, so protecting against
   * path traversal and ensuring the location is writable are the caller's responsibility.
   *
   * Thread safety, failure semantics, and document ownership follow the same rules as
   * ToHTML; see that method for details.
   *
   * @param document The PAGX document to export.
   * @param filePath The output file path, used verbatim (no validation performed by the
   *                 library).
   * @param options Export options controlling output formatting.
   * @return True on success, false if the file could not be written or the document has no
   *         content.
   */
  static bool ToFile(const PAGXDocument& document, const std::string& filePath,
                     const Options& options = {});
};

}  // namespace pagx
