/////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Tencent is pleased to support the open source community by making libpag available.
//
//  Copyright (C) 2026 Tencent. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  unless required by applicable law or agreed to in writing, software distributed under the
//  license is distributed on an "as is" basis, without warranties or conditions of any kind,
//  either express or implied. see the license for the specific language governing permissions
//  and limitations under the license.
//
/////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <memory>
#include <string>
#include <vector>
#include "pagx/layout/LayoutNode.h"
#include "pagx/nodes/Element.h"
#include "pagx/nodes/GlyphRun.h"
#include "pagx/types/Point.h"
#include "pagx/types/TextAnchor.h"
#include "pagx/types/TextBaseline.h"
#include "tgfx/core/Font.h"
#include "tgfx/core/RSXform.h"
#include "tgfx/core/Point.h"
#include "tgfx/core/TextBlob.h"

namespace pagx {

/**
 * A run of positioned glyphs with the same font, produced by the text layout engine.
 * Coordinates are in the layout coordinate system: TextBox coordinates for TextBox children,
 * Text local coordinates for standalone Text. GlyphIDs reference the original (source) font.
 */
struct TextLayoutGlyphRun {
  /**
   * The font used for rendering these glyphs.
   */
  tgfx::Font font = {};

  /**
   * Glyph IDs resolved from the text content using the font.
   */
  std::vector<tgfx::GlyphID> glyphs = {};

  /**
   * Per-glyph positions in layout coordinates. Used when glyphs have simple translations.
   */
  std::vector<tgfx::Point> positions = {};

  /**
   * Per-glyph RSXform transforms. Used when glyphs require rotation or scaling (e.g., vertical
   * text).
   */
  std::vector<tgfx::RSXform> xforms = {};
};

/**
 * Text is a geometry element that produces a glyph list after text shaping, which accumulates into
 * the rendering context for subsequent modifiers or painters. It supports two rendering modes:
 * - Pre-shaped mode: Uses GlyphRun children with precomputed glyph IDs and positions, rendered
 *   with embedded fonts to ensure cross-platform consistency.
 * - Runtime shaping mode: Performs text shaping at runtime using the text content and font
 *   properties. Results may vary slightly across platforms due to font and shaping differences.
 */
class Text : public Element, public LayoutNode {
 public:
  /**
   * The text content to render. Supports newline characters (\n) for line breaks, which use the
   * font metrics line height (ascent + descent + leading).
   */
  std::string text = {};

  /**
   * The position of the text origin (x, y where y is the baseline). The default value is (0, 0).
   */
  Point position = {};

  /**
   * The font family name (e.g., "Arial", "Helvetica"). Used for runtime shaping.
   */
  std::string fontFamily = {};

  /**
   * The font style/variant name (e.g., "Regular", "Bold", "Italic", "Bold Italic"). This
   * corresponds to the specific font file variant. The default value is an empty string, which
   * typically resolves to "Regular" during font matching.
   */
  std::string fontStyle = {};

  /**
   * The font size in pixels. The default value is 12.
   */
  float fontSize = 12.0f;

  /**
   * The letter spacing (tracking) value that adjusts spacing between characters. The default value
   * is 0.
   */
  float letterSpacing = 0.0f;

  /**
   * Whether to apply algorithmic bolding. The default value is false.
   */
  bool fauxBold = false;

  /**
   * Whether to apply algorithmic slanting. The default value is false.
   */
  bool fauxItalic = false;

  /**
   * The text anchor alignment. Controls how text is positioned relative to its origin. Start means
   * the origin is at the text start, Center centers the text on the origin, and End places the text
   * ending at the origin. Ignored when a TextBox controls the layout. The default value is Start.
   */
  TextAnchor textAnchor = TextAnchor::Start;

  /**
   * Pre-shaped glyph runs. When present, these are used for rendering instead of runtime shaping.
   */
  std::vector<GlyphRun*> glyphRuns = {};

  /**
   * Specifies how position.y is interpreted. LineBox (default): position.y is the top of the
   * linebox (based on font metrics line height). Alphabetic: position.y is the alphabetic baseline.
   */
  TextBaseline baseline = TextBaseline::LineBox;

  /**
   * Returns the TextBlob generated by TextLayout during applyLayout.
   */
  std::shared_ptr<tgfx::TextBlob> getTextBlob() const {
    return textBlob;
  }

  /**
   * Returns the per-glyph anchor point offsets generated by TextLayout. Each offset is relative to
   * the default anchor (advance * 0.5, 0) and serves as the center point for per-glyph scale,
   * rotation, and skew transforms. Empty when no text layout has been performed.
   */
  const std::vector<tgfx::Point>& getAnchors() const {
    return anchors;
  }

  /**
   * Returns the linebox bounds computed by TextLayout. For TextBox children, this is in TextBox
   * coordinate system. For standalone Text, this is in Text local coordinates.
   */
  Rect getTextBounds() const {
    return textBounds;
  }

  /**
   * Returns the layout glyph runs from runtime text shaping. Empty if using embedded GlyphRuns.
   */
  const std::vector<TextLayoutGlyphRun>& getLayoutRuns() const {
    return layoutRuns;
  }

  NodeType nodeType() const override {
    return NodeType::Text;
  }

 protected:
  void onMeasure(LayoutContext* context) override;
  void setLayoutSize(LayoutContext* context, float width, float height) override;
  void setLayoutPosition(LayoutContext* context, float x, float y) override;

 private:
  Text() = default;

  // Internal rendering attributes, written by TextLayout during applyLayout.
  std::shared_ptr<tgfx::TextBlob> textBlob = nullptr;
  std::vector<tgfx::Point> anchors = {};
  Rect textBounds = {};
  // Layout glyph runs in layout coordinate system (source font). Written by TextLayout during
  // applyLayout for runtime rendering. GlyphRunRenderer converts these to TextBlob in
  // LayerBuilder. Empty when loaded from embedded GlyphRuns (use glyphRuns instead).
  std::vector<TextLayoutGlyphRun> layoutRuns = {};

  friend class PAGXDocument;
  friend class TextBox;
  friend class TextLayout;
};

}  // namespace pagx
