# This is a basic workflow to help you get started with Actions

name: after_merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: |
          echo '${{ toJSON(github) }}'
      - name: Get environment cache
        id: cache-environment
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/Cellar/ninja
            /usr/local/bin/ninja
            /usr/local/Cellar/node
            /usr/local/bin/node
            /usr/local/Cellar/emscripten
            /usr/local/bin/emscripten
            /usr/local/Cellar/yasm
            /usr/local/bin/yasm
            /usr/local/Cellar/depsync
            /usr/local/bin/depsync
          key: libpag-environment

      - name: Get libpag cache
        id: libpag
        uses: actions/cache@v2
        with:
          path: libpag.tar.zst
          key: libpag-code-${{ github.sha }}
          restore-keys: |
            libpag-code-${{ github.event.before }}
            libpag-code-
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "libpag.tar.zst"
      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: |
          echo "file exit"
          tar xvf libpag.tar.zst
          rm -rf libpag.tar.zst
          cd libpag
          git pull
      - name: File not exists
        if: steps.check_files.outputs.files_exists != 'true'
        run: |
          echo "file not exit"
          git clone -b main https://github.com/kevingpqi123/libpag.git
          ls
          cd libpag
          ls
      - name: brew link emscripten
        if: steps.cache-third_party.outputs.cache-hit == 'true'
        run: |
           brew link emscripten

      - name: Run autotest script
        run: |
          ls
          cd libpag
          chmod +x sync_deps.sh
          ./sync_deps.sh
          chmod +x autotest.sh
          ./autotest.sh
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result
      - name: Compress libpag
        run: |
          cd libpag
          rm -rf result
          cd ..
          tar cvfa libpag.tar.zst libpag

