name: code-format

on: [push, pull_request, pull_request_target]

concurrency:
  group: code-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: clang-format (w/ diff)
  # You may pin to the exact commit or the version.
  # uses: egor-tensin/clang-format@fe6591af8142846dbc32460359045500c230f1c3
      uses: egor-tensin/clang-format@v1 
      with:
       exclude: vendor/ :qt/ :mac/ :ios/ :android/ :web/ :win/
