name: code-format

on: [push, pull_request, pull_request_target]

concurrency:
  group: code-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './src ./test'
        exclude: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: google
