name: code-format

on: [push, pull_request, pull_request_target]

concurrency:
  group: code-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-format:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        path:
          - 'src'
          - 'test'
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '13'
        check-path: ${{ matrix.path }}
