name: code-format

on:
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: './src ./test ./include ./tgfx'
          exclude: './src/platform/ios ./src/platform/mac ./test/framework/lzma'
          extensions: 'h,cpp'
          clangFormatVersion: 12