name: code-format

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]  

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run codeformat script
        run: |
          npm install -g clang-format
          clang-format --version
          chmod +x codeformat.sh
          ./codeformat.sh
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         commit_message: apply code-format changes  
