import QtQuick 2.5

ControlForm {
    // Generated by Creator, don't write code here.
}





































/*##^## Designer {
    D{i:0;autoSize:true;height:480;width:640}
}
 ##^##*/
